apiVersion: v1
kind: Pod
metadata:
  name: devwebapp
  labels:
    app: devwebapp
spec:
  containers:
    - name: app
      image: hubgab/vault_python
      env:
      - name: VAULT_ADDR
        value: "http://192.168.65.2:8200"
      - name: VAULT_TOKEN
        value: root
      - name: VAULT_SECRET_PATH
        value: devwebapp/config